// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypskvfbyauvwjiipotqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlwc2t2ZmJ5YXV2d2ppaXBvdHF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxOTI2MjAsImV4cCI6MjA4Nzc2ODYyMH0.F_v998jGVda-n0HtLDR4XKWxQ3KhAv3yE1gYNqoe3C0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});